<?php
return [
    //'test_url'=>"https://webservice.logixerp.com/webservice/v2/CreateWaybill?secureKey=-1280192700",
    //'live_url'=>"https://webservice.logixerp.com/webservice/v2/CreateWaybill?secureKey=DB7FACCA8A3640648D918B4A4818178A",
    // 'customDutyUrl' => 'http://3.90.105.99/Rachna/webservice/v2/',
    'adminEmail'           => 'dev@niletechnologies.com',
    'defaultEmail'         => 'info@niletechnologies.com',
    'defaultPhone'         => '9999999999',
    'defaultPassword'      => 'abc@123',
    'adminDefaultPerPage'  => 100,
    'eqtorUrl'             => 'https://shop.eq8tor.com/api/return/order/tracking',
    'testSecureKey'        => '-1280192700',
    'liveSecureKey'        => 'DB7FACCA8A3640648D918B4A4818178A',
    'secureKey'            => 'DB7FACCA8A3640648D918B4A4818178A',
    'AccessKey'            => 'logixerp',
    'activeUrl'            => 'https://webservice.logixerp.com/webservice/v2/',
    'cuactiveUrl'          => 'https://api.logixerp.com/webservice/v2/',
    // 'cuactiveUrl'          => 'https://egnl.logixerp.com/webservice/v2/',
    'b2cactiveUrl'         => 'https://alpha.logixerp.com/Rachna/webservice/v2',
    'b2cRetuenUrl'         => 'http://54.234.189.14/webservice/v2/',
    'reverseGearSecureKey' => 'AB7FACCA8A3JFDSE48D918BHTA4818178A',
    'customDutyUrl'        => 'https://webservice.logixerp.com/Rachna/webservice/v2/',
    'otherKey'             => '-1280192700',
    'rgUniqueId'           => 'RG',
    'rgUniqueIdMaxDigit'   => 8,
    'trackingUrl'          => 'https://webservice.logixerp.com/webservice/v1/GetTrackingByReferenceOrCarrierWayBillNumber',
    'path'                 => 'uploads/' . date("Y") . '/' . date('m') . '/',
    'upload_path'          => 'uploads/pdf_files/',
    'happyReturnStageUrl'  => 'https://partner-stage.happyreturns.com/',
    'happyReturnStageKey'  => 'fQ4PKDSwbL7oVnZGtQo1ia5Bj1sDFQo2T0TF48wq4amOIqORrTZobfU5YcHwnolD',
    'happyReturnUrl'       => 'https://partner.happyreturns.com/',
    'happyReturnKey'       => 'fQ4PKDSwbL7oVnZGtQo1ia5Bj1sDFQo2T0TF48wq4amOIqORrTZobfU5YcHwnolD',
    'oliveUrl'             => 'https://api.bigcommerce.com/stores/bbcd5/',
    'authClient'           => 'chrjqcrwi96r5jly0ya3nlpq848252u',
    'authToken'            => '4v6kvgxq0hvdaodiy2cwmc7163f027g',
    'warehouse'            => 'CHICAGO',
    'testWarehouse'        => 'Delhi',
    'dateArr'              => [
        'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December',
    ],
    'sqsRegion'            => 'eu-west-1',
    'devSQS'               => [
        'Accesskey'      => "AKIA2LHOAEUWGBMF6QAS",
        'Secretkey'      => "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",
        'SalesOrderUrl'  => 'https://sqs.eu-west-1.amazonaws.com/711316219180/mgsap-dev-pi-prj-RP-SalesOrder',
        'OrderStatusUrl' => 'https://sqs.eu-west-1.amazonaws.com/711316219180/mgsap-dev-pi-prj-RP-OrderStatus',
        'ReturnOrderUrl' => 'https://sqs.eu-west-1.amazonaws.com/711316219180/mgsap-dev-pi-prj-RP-ReturnOrder',
        'CarrierMgmtUrl' => 'https://sqs.eu-west-1.amazonaws.com/711316219180/mgsap-dev-pi-prj-RP-CarrierMgmt',
    ],
    'qaSQS'                => [
        'Accesskey'      => "AKIA2LHOAEUWOHDNUH5W",
        'Secretkey'      => "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",
        'SalesOrderUrl'  => 'https://sqs.eu-west-1.amazonaws.com/711316219180/mgsap-qa-piapp-q-RP-SalesOrder',
        'OrderStatusUrl' => 'https://sqs.eu-west-1.amazonaws.com/711316219180/mgsap-qa-piapp-q-RP-OrderStatus',
        'ReturnOrderUrl' => 'https://sqs.eu-west-1.amazonaws.com/711316219180/mgsap-qa-piapp-q-RP-ReturnOrder',
        'CarrierMgmtUrl' => 'https://sqs.eu-west-1.amazonaws.com/711316219180/mgsap-qa-piapp-q-RP-CarrierMgmt',
    ],
    'liveSQS'              => [
        'Accesskey'      => "AKIA3PQVI7D777JVG4X7",
        'Secretkey'      => "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",
        'SalesOrderUrl'  => "https://sqs.eu-west-1.amazonaws.com/789244868863/mgsap-prod-piapp-p-RP-SalesOrder",
        'OrderStatusUrl' => "https://sqs.eu-west-1.amazonaws.com/789244868863/mgsap-prod-piapp-p-RP-OrderStatus",
        'ReturnOrderUrl' => "https://sqs.eu-west-1.amazonaws.com/789244868863/mgsap-prod-piapp-p-RP-ReturnOrder",
        'CarrierMgmtUrl' => "https://sqs.eu-west-1.amazonaws.com/789244868863/mgsap-prod-piapp-p-RP-CarrierMgmt",
    ],
];
